version: '3.8'

services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - "4444:4444"
    environment:
      - GRID_MAX_SESSION=5
      - GRID_BROWSER_TIMEOUT=300
      - GRID_TIMEOUT=300
    networks:
      - selenium-grid

  chrome-node-1:
    image: selenium/node-chrome:latest
    container_name: chrome-node-1
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=300
      - JAVA_OPTS=-Xmx512m
    shm_size: '1gb'
    mem_limit: 1g
    cpus: 0.5
    networks:
      - selenium-grid

  chrome-node-2:
    image: selenium/node-chrome:latest
    container_name: chrome-node-2
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=1
      - SE_NODE_SESSION_TIMEOUT=300
      - JAVA_OPTS=-Xmx512m
    shm_size: '1gb'
    mem_limit: 1g
    cpus: 0.5
    networks:
      - selenium-grid

  scraper-api:
    build:
      context: .
      dockerfile: Dockerfile.selenium
    container_name: ebay-scraper-api
    ports:
      - "8000:8000"
    depends_on:
      - selenium-hub
    environment:
      - SELENIUM_HUB_URL=http://selenium-hub:4444
      - MAX_WORKERS=2
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./results:/app/results
    networks:
      - selenium-grid

  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - "6379:6379"
    mem_limit: 256m
    networks:
      - selenium-grid

networks:
  selenium-grid:
    driver: bridge